name: Deploy Frontend to S3

on:
  push:
    branches:
      - main
    paths:
      - frontend/resume.html
      - frontend/style.css
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: "--delete --exact-timestamps --exclude '*' --include 'resume.html' --include 'style.css'"

        env:
          AWS_S3_BUCKET: resume-drakepwj.click
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          SOURCE_DIR: frontend/
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ETBAFHJGA5OFC \
            --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2

